# permissions for end users to view apisixclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisixcluster-viewer-role
rules:
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixclusters/status
  verbs:
  - get
